sudo: required
dist: trusty
language: c
compiler:
  - gcc
  - clang
addons:
  # See http://docs.travis-ci.com/user/apt/
  apt:
    packages:
    - libconfuse-dev
    - libyajl-dev
    - libasound2-dev
    - libpulse-dev
    - libnl-genl-3-dev
    - asciidoc
    # xmlto pulls in a2x which we need for generating manpages from asciidoc.
    - xmlto
    - libcap2-bin
    - clang-format-3.5
    - libllvm3.5
script:
  - make -j
  - clang-format-3.5 -i $(find . -name "*.[ch]" | tr '\n' ' ') && git diff --exit-code || (echo 'Code was not formatted using clang-format!'; false)
