os: linux
dist: trusty
language: c

compiler:
  - gcc
  - clang
addons:
  # See http://docs.travis-ci.com/user/apt/
  apt:
    packages:
    - libconfuse-dev
    - libyajl-dev
    - libasound2-dev
    - libpulse-dev
    - libnl-genl-3-dev
    - asciidoc
    # xmlto pulls in a2x which we need for generating manpages from asciidoc.
    - xmlto
    - libcap2-bin
    - clang-format-3.8
    - libllvm3.5
    - pulseaudio
script:
  - clang-format-3.8 -i $(find . -name "*.[ch]" | tr '\n' ' ') && git diff --exit-code || (echo 'Code was not formatted using clang-format!'; false)
  # TODO: re-enable sanitizers once issues are fixed
  - autoreconf -fi && mkdir -p build && cd build && (../configure --disable-sanitizers || (cat config.log; false)) && make -j 8 V=1 && ldd ./i3status |& grep -q pulse || (echo "not linked against pulseaudio"; exit 1)
  - make clean && (../configure --disable-sanitizers --disable-pulseaudio || (cat config.log; false)) && make -j 8 V=1 && ldd ./i3status |& grep -q pulse && (echo "linked against pulseaudio"; exit 1) || true
  - make -j 8 check V=1 || (cat test-suite.log; false)
